# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/ran/Programs/clion-2019.3.2/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/ran/Programs/clion-2019.3.2/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ran/Documents/Playground/MinkowskiEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ran/Documents/Playground/MinkowskiEngine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/ran/Programs/clion-2019.3.2/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/ran/Programs/clion-2019.3.2/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ran/Documents/Playground/MinkowskiEngine/CMakeFiles /home/ran/Documents/Playground/MinkowskiEngine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ran/Documents/Playground/MinkowskiEngine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named minkowski

# Build rule for target.
minkowski: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 minkowski
.PHONY : minkowski

# fast build rule for target.
minkowski/fast:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/build
.PHONY : minkowski/fast

pybind/minkowski.o: pybind/minkowski.cpp.o

.PHONY : pybind/minkowski.o

# target to build an object file
pybind/minkowski.cpp.o:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/pybind/minkowski.cpp.o
.PHONY : pybind/minkowski.cpp.o

pybind/minkowski.i: pybind/minkowski.cpp.i

.PHONY : pybind/minkowski.i

# target to preprocess a source file
pybind/minkowski.cpp.i:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/pybind/minkowski.cpp.i
.PHONY : pybind/minkowski.cpp.i

pybind/minkowski.s: pybind/minkowski.cpp.s

.PHONY : pybind/minkowski.s

# target to generate assembly for a file
pybind/minkowski.cpp.s:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/pybind/minkowski.cpp.s
.PHONY : pybind/minkowski.cpp.s

src/broadcast.o: src/broadcast.cpp.o

.PHONY : src/broadcast.o

# target to build an object file
src/broadcast.cpp.o:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/broadcast.cpp.o
.PHONY : src/broadcast.cpp.o

src/broadcast.i: src/broadcast.cpp.i

.PHONY : src/broadcast.i

# target to preprocess a source file
src/broadcast.cpp.i:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/broadcast.cpp.i
.PHONY : src/broadcast.cpp.i

src/broadcast.s: src/broadcast.cpp.s

.PHONY : src/broadcast.s

# target to generate assembly for a file
src/broadcast.cpp.s:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/broadcast.cpp.s
.PHONY : src/broadcast.cpp.s

src/convolution.o: src/convolution.cpp.o

.PHONY : src/convolution.o

# target to build an object file
src/convolution.cpp.o:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/convolution.cpp.o
.PHONY : src/convolution.cpp.o

src/convolution.i: src/convolution.cpp.i

.PHONY : src/convolution.i

# target to preprocess a source file
src/convolution.cpp.i:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/convolution.cpp.i
.PHONY : src/convolution.cpp.i

src/convolution.s: src/convolution.cpp.s

.PHONY : src/convolution.s

# target to generate assembly for a file
src/convolution.cpp.s:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/convolution.cpp.s
.PHONY : src/convolution.cpp.s

src/convolution_transpose.o: src/convolution_transpose.cpp.o

.PHONY : src/convolution_transpose.o

# target to build an object file
src/convolution_transpose.cpp.o:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/convolution_transpose.cpp.o
.PHONY : src/convolution_transpose.cpp.o

src/convolution_transpose.i: src/convolution_transpose.cpp.i

.PHONY : src/convolution_transpose.i

# target to preprocess a source file
src/convolution_transpose.cpp.i:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/convolution_transpose.cpp.i
.PHONY : src/convolution_transpose.cpp.i

src/convolution_transpose.s: src/convolution_transpose.cpp.s

.PHONY : src/convolution_transpose.s

# target to generate assembly for a file
src/convolution_transpose.cpp.s:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/convolution_transpose.cpp.s
.PHONY : src/convolution_transpose.cpp.s

src/coords_key.o: src/coords_key.cpp.o

.PHONY : src/coords_key.o

# target to build an object file
src/coords_key.cpp.o:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/coords_key.cpp.o
.PHONY : src/coords_key.cpp.o

src/coords_key.i: src/coords_key.cpp.i

.PHONY : src/coords_key.i

# target to preprocess a source file
src/coords_key.cpp.i:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/coords_key.cpp.i
.PHONY : src/coords_key.cpp.i

src/coords_key.s: src/coords_key.cpp.s

.PHONY : src/coords_key.s

# target to generate assembly for a file
src/coords_key.cpp.s:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/coords_key.cpp.s
.PHONY : src/coords_key.cpp.s

src/coords_manager.o: src/coords_manager.cpp.o

.PHONY : src/coords_manager.o

# target to build an object file
src/coords_manager.cpp.o:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/coords_manager.cpp.o
.PHONY : src/coords_manager.cpp.o

src/coords_manager.i: src/coords_manager.cpp.i

.PHONY : src/coords_manager.i

# target to preprocess a source file
src/coords_manager.cpp.i:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/coords_manager.cpp.i
.PHONY : src/coords_manager.cpp.i

src/coords_manager.s: src/coords_manager.cpp.s

.PHONY : src/coords_manager.s

# target to generate assembly for a file
src/coords_manager.cpp.s:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/coords_manager.cpp.s
.PHONY : src/coords_manager.cpp.s

src/coordsmap.o: src/coordsmap.cpp.o

.PHONY : src/coordsmap.o

# target to build an object file
src/coordsmap.cpp.o:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/coordsmap.cpp.o
.PHONY : src/coordsmap.cpp.o

src/coordsmap.i: src/coordsmap.cpp.i

.PHONY : src/coordsmap.i

# target to preprocess a source file
src/coordsmap.cpp.i:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/coordsmap.cpp.i
.PHONY : src/coordsmap.cpp.i

src/coordsmap.s: src/coordsmap.cpp.s

.PHONY : src/coordsmap.s

# target to generate assembly for a file
src/coordsmap.cpp.s:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/coordsmap.cpp.s
.PHONY : src/coordsmap.cpp.s

src/math_functions.o: src/math_functions.cpp.o

.PHONY : src/math_functions.o

# target to build an object file
src/math_functions.cpp.o:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/math_functions.cpp.o
.PHONY : src/math_functions.cpp.o

src/math_functions.i: src/math_functions.cpp.i

.PHONY : src/math_functions.i

# target to preprocess a source file
src/math_functions.cpp.i:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/math_functions.cpp.i
.PHONY : src/math_functions.cpp.i

src/math_functions.s: src/math_functions.cpp.s

.PHONY : src/math_functions.s

# target to generate assembly for a file
src/math_functions.cpp.s:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/math_functions.cpp.s
.PHONY : src/math_functions.cpp.s

src/pooling_avg.o: src/pooling_avg.cpp.o

.PHONY : src/pooling_avg.o

# target to build an object file
src/pooling_avg.cpp.o:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/pooling_avg.cpp.o
.PHONY : src/pooling_avg.cpp.o

src/pooling_avg.i: src/pooling_avg.cpp.i

.PHONY : src/pooling_avg.i

# target to preprocess a source file
src/pooling_avg.cpp.i:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/pooling_avg.cpp.i
.PHONY : src/pooling_avg.cpp.i

src/pooling_avg.s: src/pooling_avg.cpp.s

.PHONY : src/pooling_avg.s

# target to generate assembly for a file
src/pooling_avg.cpp.s:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/pooling_avg.cpp.s
.PHONY : src/pooling_avg.cpp.s

src/pooling_global_avg.o: src/pooling_global_avg.cpp.o

.PHONY : src/pooling_global_avg.o

# target to build an object file
src/pooling_global_avg.cpp.o:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/pooling_global_avg.cpp.o
.PHONY : src/pooling_global_avg.cpp.o

src/pooling_global_avg.i: src/pooling_global_avg.cpp.i

.PHONY : src/pooling_global_avg.i

# target to preprocess a source file
src/pooling_global_avg.cpp.i:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/pooling_global_avg.cpp.i
.PHONY : src/pooling_global_avg.cpp.i

src/pooling_global_avg.s: src/pooling_global_avg.cpp.s

.PHONY : src/pooling_global_avg.s

# target to generate assembly for a file
src/pooling_global_avg.cpp.s:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/pooling_global_avg.cpp.s
.PHONY : src/pooling_global_avg.cpp.s

src/pooling_global_max.o: src/pooling_global_max.cpp.o

.PHONY : src/pooling_global_max.o

# target to build an object file
src/pooling_global_max.cpp.o:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/pooling_global_max.cpp.o
.PHONY : src/pooling_global_max.cpp.o

src/pooling_global_max.i: src/pooling_global_max.cpp.i

.PHONY : src/pooling_global_max.i

# target to preprocess a source file
src/pooling_global_max.cpp.i:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/pooling_global_max.cpp.i
.PHONY : src/pooling_global_max.cpp.i

src/pooling_global_max.s: src/pooling_global_max.cpp.s

.PHONY : src/pooling_global_max.s

# target to generate assembly for a file
src/pooling_global_max.cpp.s:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/pooling_global_max.cpp.s
.PHONY : src/pooling_global_max.cpp.s

src/pooling_max.o: src/pooling_max.cpp.o

.PHONY : src/pooling_max.o

# target to build an object file
src/pooling_max.cpp.o:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/pooling_max.cpp.o
.PHONY : src/pooling_max.cpp.o

src/pooling_max.i: src/pooling_max.cpp.i

.PHONY : src/pooling_max.i

# target to preprocess a source file
src/pooling_max.cpp.i:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/pooling_max.cpp.i
.PHONY : src/pooling_max.cpp.i

src/pooling_max.s: src/pooling_max.cpp.s

.PHONY : src/pooling_max.s

# target to generate assembly for a file
src/pooling_max.cpp.s:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/pooling_max.cpp.s
.PHONY : src/pooling_max.cpp.s

src/pooling_transpose.o: src/pooling_transpose.cpp.o

.PHONY : src/pooling_transpose.o

# target to build an object file
src/pooling_transpose.cpp.o:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/pooling_transpose.cpp.o
.PHONY : src/pooling_transpose.cpp.o

src/pooling_transpose.i: src/pooling_transpose.cpp.i

.PHONY : src/pooling_transpose.i

# target to preprocess a source file
src/pooling_transpose.cpp.i:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/pooling_transpose.cpp.i
.PHONY : src/pooling_transpose.cpp.i

src/pooling_transpose.s: src/pooling_transpose.cpp.s

.PHONY : src/pooling_transpose.s

# target to generate assembly for a file
src/pooling_transpose.cpp.s:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/pooling_transpose.cpp.s
.PHONY : src/pooling_transpose.cpp.s

src/pruning.o: src/pruning.cpp.o

.PHONY : src/pruning.o

# target to build an object file
src/pruning.cpp.o:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/pruning.cpp.o
.PHONY : src/pruning.cpp.o

src/pruning.i: src/pruning.cpp.i

.PHONY : src/pruning.i

# target to preprocess a source file
src/pruning.cpp.i:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/pruning.cpp.i
.PHONY : src/pruning.cpp.i

src/pruning.s: src/pruning.cpp.s

.PHONY : src/pruning.s

# target to generate assembly for a file
src/pruning.cpp.s:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/pruning.cpp.s
.PHONY : src/pruning.cpp.s

src/quantization.o: src/quantization.cpp.o

.PHONY : src/quantization.o

# target to build an object file
src/quantization.cpp.o:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/quantization.cpp.o
.PHONY : src/quantization.cpp.o

src/quantization.i: src/quantization.cpp.i

.PHONY : src/quantization.i

# target to preprocess a source file
src/quantization.cpp.i:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/quantization.cpp.i
.PHONY : src/quantization.cpp.i

src/quantization.s: src/quantization.cpp.s

.PHONY : src/quantization.s

# target to generate assembly for a file
src/quantization.cpp.s:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/quantization.cpp.s
.PHONY : src/quantization.cpp.s

src/region.o: src/region.cpp.o

.PHONY : src/region.o

# target to build an object file
src/region.cpp.o:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/region.cpp.o
.PHONY : src/region.cpp.o

src/region.i: src/region.cpp.i

.PHONY : src/region.i

# target to preprocess a source file
src/region.cpp.i:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/region.cpp.i
.PHONY : src/region.cpp.i

src/region.s: src/region.cpp.s

.PHONY : src/region.s

# target to generate assembly for a file
src/region.cpp.s:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/region.cpp.s
.PHONY : src/region.cpp.s

src/union.o: src/union.cpp.o

.PHONY : src/union.o

# target to build an object file
src/union.cpp.o:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/union.cpp.o
.PHONY : src/union.cpp.o

src/union.i: src/union.cpp.i

.PHONY : src/union.i

# target to preprocess a source file
src/union.cpp.i:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/union.cpp.i
.PHONY : src/union.cpp.i

src/union.s: src/union.cpp.s

.PHONY : src/union.s

# target to generate assembly for a file
src/union.cpp.s:
	$(MAKE) -f CMakeFiles/minkowski.dir/build.make CMakeFiles/minkowski.dir/src/union.cpp.s
.PHONY : src/union.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... minkowski"
	@echo "... pybind/minkowski.o"
	@echo "... pybind/minkowski.i"
	@echo "... pybind/minkowski.s"
	@echo "... src/broadcast.o"
	@echo "... src/broadcast.i"
	@echo "... src/broadcast.s"
	@echo "... src/convolution.o"
	@echo "... src/convolution.i"
	@echo "... src/convolution.s"
	@echo "... src/convolution_transpose.o"
	@echo "... src/convolution_transpose.i"
	@echo "... src/convolution_transpose.s"
	@echo "... src/coords_key.o"
	@echo "... src/coords_key.i"
	@echo "... src/coords_key.s"
	@echo "... src/coords_manager.o"
	@echo "... src/coords_manager.i"
	@echo "... src/coords_manager.s"
	@echo "... src/coordsmap.o"
	@echo "... src/coordsmap.i"
	@echo "... src/coordsmap.s"
	@echo "... src/math_functions.o"
	@echo "... src/math_functions.i"
	@echo "... src/math_functions.s"
	@echo "... src/pooling_avg.o"
	@echo "... src/pooling_avg.i"
	@echo "... src/pooling_avg.s"
	@echo "... src/pooling_global_avg.o"
	@echo "... src/pooling_global_avg.i"
	@echo "... src/pooling_global_avg.s"
	@echo "... src/pooling_global_max.o"
	@echo "... src/pooling_global_max.i"
	@echo "... src/pooling_global_max.s"
	@echo "... src/pooling_max.o"
	@echo "... src/pooling_max.i"
	@echo "... src/pooling_max.s"
	@echo "... src/pooling_transpose.o"
	@echo "... src/pooling_transpose.i"
	@echo "... src/pooling_transpose.s"
	@echo "... src/pruning.o"
	@echo "... src/pruning.i"
	@echo "... src/pruning.s"
	@echo "... src/quantization.o"
	@echo "... src/quantization.i"
	@echo "... src/quantization.s"
	@echo "... src/region.o"
	@echo "... src/region.i"
	@echo "... src/region.s"
	@echo "... src/union.o"
	@echo "... src/union.i"
	@echo "... src/union.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

